# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/
sudo: required

language: ruby

rvm:
  - 2.3

services:
  - docker

env:
  - IMAGE_NAME=azure-loadbalancer-module

jobs:
  include:
    - stage: rake build
      install: true
      script:
      - docker build -t ${IMAGE_NAME} .
      - docker run ${IMAGE_NAME} rake build
